---
ci:
    skip:
    - hadolint
    - shellcheck
    - shfmt

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: file-contents-sorter
    files: requirements/(base|dev|test).in
    args: [--ignore-case, --unique]
  - id: fix-byte-order-marker
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: "5.13.2"
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: "7.1.1"
  hooks:
  - id: flake8
- repo: https://github.com/ikamensh/flynt
  rev: "1.0.1"
  hooks:
  - id: flynt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args: [--py311-plus]
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [--strict]
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.0
  hooks:
  - id: codespell
- repo: https://github.com/hadolint/hadolint
  rev: v2.13.1-beta
  hooks:
  - id: hadolint
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: "3.0.0"
  hooks:
  - id: shellcheck
  - id: script-must-have-extension
  - id: shfmt
