---
ci:
    skip:
    - hadolint
    - shellcheck
    - shfmt

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: file-contents-sorter
    files: requirements/(base|dev|test).in
    args: [--ignore-case, --unique]
  - id: fix-byte-order-marker
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: "5.12.0"
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: "6.0.0"
  hooks:
  - id: flake8
- repo: https://github.com/ikamensh/flynt
  rev: "0.78"
  hooks:
  - id: flynt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py311-plus]
- repo: https://github.com/adrienverge/yamllint
  rev: v1.30.0
  hooks:
  - id: yamllint
    args: [--strict]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.1-beta
  hooks:
  - id: hadolint
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: "3.0.0"
  hooks:
  - id: shellcheck
  - id: script-must-have-extension
  - id: shfmt
