[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = ["relbot"]
line_length = 88
multi_line_output = 3
use_parentheses = true
